### ISSUE TITLE
(Website-) Problem bei Abfrage der API

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#217] opened 2019-10-16 13:54 UTC
HSK-Webadmin schreibt

> Wir haben eine Meldung von Snowflake bekommen, dass es einen Fehler beim MAdeK-Import gibt. 
> Hier die Analyse von Snowflake (Nicolas Karrer):
>  
> Die Madek Antworten stimmen nicht. 
>  
> Wenn wir die Madek API das erste Mal aufrufen tun wir das mit folgendem Link: 
https://medienarchiv.zhdk.ch/api/collections/?collection_id=4015e1d2-db38-4f7e-8118-b54ab416a6c5&public_get_metadata_and_previews=1&page=1 
> (Das funktioniert)
> 
> Wir prüfen, ob mehr Daten vorhanden sind, und rufen dann die API wieder auf mit folgendem Eintrag aus der Antwort der API: 
> _json_roa -> collection -> next -> href
> 
> Dieser Eintrag sieht momentan so aus: 
> 
> /api/collections/?collection_id=4015e1d2-db38-4f7e-8118-b54ab416a6c5&public_get_metadata_and_previews=1&page=2&public_get_metadata_and_previews=1&collection_id=4015e1d2-db38-4f7e-8118-b54ab416a6c5
> 
> (was m.E. falsch ist, da collection_id und public_get_metadata_and_preview doppelt gesetzt sind)
> 
> Wenn wir die Madek API mit diesem Link aufrufen erhalten wir einen Fehler von der Madek:
> 
> 500 Internal Server Error
{"message":"ERROR: syntax error at or near \"d2\"
Position: 168"}
> 
> Dann schlägt der Import fehl.

**Comment by nimaai** [comment] 2019-10-16 19:43
Immediate cause of the problem is here: https://github.com/Madek/madek-api/blob/master/src/madek/api/resources/collections/index.clj#L26

Two things can happen:
1. `collection_id` is a string (appears only once in query params), then fine.
2. `collection_id` is a vector (appears multiple times in query params), then bang. HoneySQL would need a `:in` instead of `:=` in the where condition to generate a valid SQL string.

Mind this: the check condition `(seq collection_id)` is true in both above cases.

There are multiple possible solutions of the issue. I don't know which is the most suitable and sustainable one. Let me enumerate:
1. Make the SQL query builder mentioned above more flexible to deal with a single collection ID or multiple ones. But, is the use case of multiple collection IDs a valid one at all? 
2. Remove `collection_id` (and possibly others too) from the templated URL here: https://github.com/Madek/madek-api/blob/master/src/madek/api/json_roa/links.clj#L187. I am not sure if this is a good idea. But why are e.g. collections templated and meta keys not?
3. Deal with the issue of duplicate params (query + template) ourselves in our `path` functions before we pass it on the the URI template library to generate the final href.
4. Blackmail the author(s) of the URI template library to change their implementation and fix the problem for us.

@DrTom @eins78

**Comment by eins78** [comment] 2019-10-17 07:23
We need at least `2.` to fix the bug the API consumer is currently facing, and `1.` for completeness. Put another way: using `ROA` means we don't expect clients to construct arbitrary URLs, so the ones we give them should work; but it still should correctly handle errors like unexpected params (e.g. `HTTP Error 422`).

`3.` is not really an option because there is no standard way on how to interpret with duplicate params (this is also just one of the reasons against `4.` ;))

**Comment by eins78** [comment] 2019-10-18 08:52
fixed in https://github.com/Madek/madek-api/commit/f9cc1f0b913bded9de8158b086ee408e3c82781d

released in 3.28.2 https://github.com/Madek/madek/commit/cd431e4b5cbbf7a47f58a2a87a8894038390efa8
https://github.com/Madek/madek/milestone/17

**Closed by eins78** 2019-10-18 08:52 UTC
Labels: High Prio Bug
